# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

env: 
  BRANCH_NAME: '565-en-folders-and-user-guide'
  BUILD_DOCS_BRANCH: 'prefix-dest-with-en'

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["565-en-folders-and-user-guide"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "${{env.BRANCH_NAME}}"
          path: "content-repo"
      - name: Inspect directory
        shell: pwsh
        run: |
          $content = Get-ChildItem
          Write-Host "$($content)"

